name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      # - name: ğŸ“¦ Setup pnpm cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.pnpm-store
      #       node_modules/.cache
      #       ${{ github.workspace }}/.next/cache
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-
      #       ${{ runner.os }}-

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ” Run linting
        run: pnpm lint

      - name: ğŸ§ª Run tests
        run: pnpm test

  build-preview:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0

      - name: ğŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸš€ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ— Build preview
        run: eas build --platform ios --profile development --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}

  build-production:
    needs: test
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸš€ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ— Build production
        run: eas build --platform all --profile production --non-interactive --no-wait
